Repository microsoft/vscode-docker, pull requests merged in 2018-08, with the labels that each got.

#345 Improve AsyncPool.test.ts speed
  test/asyncpool.test.ts
Labels: Engineering

#348 Debug telemetry reporter
  .vscode/launch.json
  dockerExtension.ts
  extensionVariables.ts
  package.json
  telemetry/telemetry.ts
Labels: Engineering

#350 Switch to shared telemetry
  dockerExtension.ts
  package.json
Labels: Engineering

#278 Remove deprecated "go-wrapper" script
  configureWorkspace/configure.ts
Labels: needs more info

#356 Add a Build Image test
  .travis.yml
  commands/build-image.ts
  commands/docker-compose.ts
  commands/open-shell-container.ts
  commands/push-image.ts
  commands/showlogs-container.ts
  commands/start-container.ts
  commands/system-prune.ts
  commands/utils/TerminalProvider.ts
  commands/utils/create-terminal.ts
  configureWorkspace/config-utils.ts
  dockerExtension.ts
  dockerHubApi.ts
  explorer/deploy/util.ts
  explorer/deploy/webAppCreator.ts
  explorer/models/azureRegistryNodes.ts
  explorer/models/registryRootNode.ts
  extensionVariables.ts
  package.json
  test/assertEx.ts
  test/buildAndRun.test.ts
  test/configure.test.ts
  test/global.test.ts
  test/index.ts
  utils/httpRequest.ts
Labels: Engineering

#367 Simplify command conditions in package.json
  package.json
Labels: Engineering

#368 Move/organize some constants
  constants.ts
  dockerExtension.ts
  explorer/models/azureRegistryNodes.ts
  explorer/models/dockerHubNodes.ts
  explorer/models/registryRootNode.ts
  explorer/utils/dockerHubUtils.ts
  utils/azureUtilityManager.ts
  utils/constants.ts
Labels: Engineering

#385 Copyright headers
  commands/build-image.ts
  commands/docker-compose.ts
  commands/inspect-image.ts
  commands/open-shell-container.ts
  commands/push-image.ts
  commands/remove-container.ts
  commands/remove-image.ts
  commands/restart-container.ts
  commands/showlogs-container.ts
  commands/start-container.ts
  commands/stop-container.ts
  commands/system-prune.ts
  commands/tag-image.ts
  commands/utils/TerminalProvider.ts
  commands/utils/docker-endpoint.ts
  commands/utils/quick-pick-container.ts
  commands/utils/quick-pick-image.ts
  configureWorkspace/config-utils.ts
  configureWorkspace/configDebugProvider.ts
  configureWorkspace/configure.ts
  constants.ts
  dockerCompose/dockerComposeCompletionItemProvider.ts
  dockerCompose/dockerComposeHoverProvider.ts
  dockerCompose/dockerComposeKeyInfo.ts
  dockerCompose/dockerComposeParser.ts
  dockerExtension.ts
  dockerHubApi.ts
  dockerfile/dockerfileCompletionItemProvider.ts
  documentContentProviders/dockerInspect.ts
  explorer/deploy/azureAccountWrapper.ts
  explorer/deploy/util.ts
  explorer/deploy/webAppCreator.ts
  explorer/deploy/wizard.ts
  explorer/dockerExplorer.ts
  explorer/models/azureRegistryNodes.ts
  explorer/models/containerNode.ts
  explorer/models/dockerHubNodes.ts
  explorer/models/imageNode.ts
  explorer/models/nodeBase.ts
  explorer/models/registryRootNode.ts
  explorer/models/registryType.ts
  explorer/models/rootNode.ts
  explorer/utils/azureUtils.ts
  explorer/utils/dockerHubUtils.ts
  explorer/utils/utils.ts
  extensionVariables.ts
  gulpfile.js
  helpers/async.ts
  helpers/suggestSupportHelper.ts
  parser.ts
  telemetry/telemetry.ts
  test/assertEx.test.ts
  test/assertEx.ts
  test/global.test.ts
  test/index.ts
  utils/asyncpool.ts
  utils/azureUtilityManager.ts
  utils/httpRequest.ts
Labels: Engineering

#366 Add configure command telemetry, plus code improvements
  .vscode/tasks.json
  configureWorkspace/configure.ts
  dockerExtension.ts
  test/buildAndRun.test.ts
  test/configure.test.ts
Labels: Engineering

#378 Improve build-image and fix some strict typescript issues
  commands/build-image.ts
  commands/utils/quick-pick-container.ts
  dockerCompose/dockerComposeParser.ts
  dockerExtension.ts
  dockerHubApi.ts
  explorer/dockerExplorer.ts
  helpers/suggestSupportHelper.ts
  test/asyncpool.test.ts
  test/global.test.ts
Labels: Engineering

#387 Allow setting mocha options in launch.json
  .vscode/launch.json
  test/buildAndRun.test.ts
  test/index.ts
Labels: Engineering

#388 Add API to control Add dockerfiles command
  configureWorkspace/configure.ts
  dockerExtension.ts
  explorer/utils/azureUtils.ts
  explorer/utils/dockerHubUtils.ts
  package.json
  test/buildAndRun.test.ts
  test/configure.test.ts
  test/global.test.ts
  test/index.ts
Labels: enhancement

#413 Remove unused DockerHubOrgNode.repository
  explorer/models/dockerHubNodes.ts
  explorer/utils/dockerHubUtils.ts
Labels: Engineering

#414 Let vscode reformat package.json, no changes
  package.json
Labels: Engineering

#392 Adopt version 0.0.19 of the language server
  package.json
Labels: P1
