Repository microsoft/vscode-docker, pull requests merged in 2021-08, with the labels that each got.

#3117 Update version, changelog, notices for 1.16.0
  CHANGELOG.md
  NOTICE.html
  package-lock.json
  package.json
Labels: engineering

#3121 Upgrade to language server 0.5.0
  package-lock.json
  package.json
Labels: language-server

#3144 Bump version to 1.16.5-alpha
  package-lock.json
  package.json
Labels: engineering

#3146 Bump dependencies
  package-lock.json
  package.json
  src/commands/registries/azure/DockerSiteCreateStep.ts
  src/commands/registries/azure/DockerWebhookCreateStep.ts
  src/commands/registries/azure/openInAzurePortal.ts
  src/commands/registries/azure/tasks/runAzureTask.ts
  src/commands/registries/azure/tasks/scheduleRunRequest.ts
  src/commands/registries/azure/tasks/viewAzureTaskLogs.ts
  src/tree/registries/azure/AzureRegistryTreeItem.ts
  src/tree/registries/azure/AzureTaskTreeItem.ts
  src/tree/registries/azure/AzureTasksTreeItem.ts
  src/tree/registries/azure/SubscriptionTreeItem.ts
Labels: engineering

#3157 Remove experiment for context lookup
  src/docker/ContextManager.ts
Labels: engineering, experimentation
