Repository microsoft/vscode-docker, pull requests merged in 2022-02, with the labels that each got.

#3414 Fix unit tests failing in new VSCode version
  src/telemetry/ActivityMeasurementService.ts
  src/test/telemetry/ActivityMeasurementService.test.ts
Labels: engineering

#3415 Include different delimiter for Date
  src/docker/files/ContainerFilesUtils.ts
Labels: fixed in next release

#3417 Run `npm audit fix`
  package-lock.json
Labels: engineering, dependencies

#3423 Update compose language service
  package-lock.json
  package.json
Labels: dependencies

#3418 Update version, changelog, notices for 1.20.0
  CHANGELOG.md
  NOTICE.html
  package-lock.json
  package.json
Labels: engineering

#3433 Change some TS rules and fix
  src/docker/ContextManager.ts
  src/tasks/python/PythonTaskHelper.ts
  src/test/utils/commandLineBuilder.test.ts
  src/tree/contexts/ContextTreeItem.ts
  src/utils/quickPickFile.ts
  tsconfig.json
Labels: engineering
